### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by janheinrichmerker** [nehasrikn/pragmatic-inferences-qa#1]
I recently stumbled upon your paper "Pregnant Questions: The Importance of Pragmatic Awareness in Maternal Health Question Answering" which links to this repository for the dataset.
Is there a way to download the dataset to re-use it in further research?

**Comment by nehasrikn** [comment]
Yes! All uploaded. There is a notebook in there for how to load/view data. Let us know if you have any questions or send an email to nehasrik@umd.edu!

**Comment by janheinrichmerker** [comment]
Thank you!
